"""phase 5 citation trust system

Revision ID: 115365d6f3ea
Revises: 85a3b16a35fa
Create Date: 2026-07-19 17:51:25.530813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '115365d6f3ea'
down_revision: Union[str, None] = '85a3b16a35fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_messages', sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_messages', 'citations')
    # ### end Alembic commands ###
