"""feature 12 ai training center

Revision ID: 243da8c67976
Revises: 3764d0546fd8
Create Date: 2026-07-19 22:35:42.287833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '243da8c67976'
down_revision: Union[str, None] = '3764d0546fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('MISSING_KNOWLEDGE', 'PROMPT_IMPROVEMENT', 'WORKFLOW_IMPROVEMENT', name='insight_category'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('supporting_call_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ACKNOWLEDGED', 'DISMISSED', name='insight_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON training_insights TO app_user")
    op.execute("ALTER TABLE training_insights ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE training_insights FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON training_insights "
        "USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid)"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_insights')
    # ### end Alembic commands ###
