"""feature 11 ai quality analyst

Revision ID: 3764d0546fd8
Revises: 8293d46e7628
Create Date: 2026-07-19 22:20:01.902932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3764d0546fd8'
down_revision: Union[str, None] = '8293d46e7628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('accuracy_score', sa.Float(), nullable=True))
    op.add_column('calls', sa.Column('compliance_score', sa.Float(), nullable=True))
    op.add_column('calls', sa.Column('empathy_score', sa.Float(), nullable=True))
    op.add_column('calls', sa.Column('resolution_score', sa.Float(), nullable=True))
    op.add_column('calls', sa.Column('qa_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'qa_notes')
    op.drop_column('calls', 'resolution_score')
    op.drop_column('calls', 'empathy_score')
    op.drop_column('calls', 'compliance_score')
    op.drop_column('calls', 'accuracy_score')
    # ### end Alembic commands ###
