"""feature 10 supervisor command center

Revision ID: 509824895eeb
Revises: 174c263c163f
Create Date: 2026-07-19 22:53:26.511286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '509824895eeb'
down_revision: Union[str, None] = '174c263c163f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('ai_paused', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('calls', sa.Column('pending_suggestion', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'pending_suggestion')
    op.drop_column('calls', 'ai_paused')
    # ### end Alembic commands ###
