"""phase 9 multi agent department field

Revision ID: 8293d46e7628
Revises: 5d0f2306596d
Create Date: 2026-07-19 22:02:53.228189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8293d46e7628'
down_revision: Union[str, None] = '5d0f2306596d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'agents', sa.Column('department', sa.String(length=50), nullable=False, server_default='general')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'department')
    # ### end Alembic commands ###
