"""phase 1 conversation storage and call memory

Revision ID: 85a3b16a35fa
Revises: d18b0ec02d0a
Create Date: 2026-07-19 17:34:26.617489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '85a3b16a35fa'
down_revision: Union[str, None] = 'd18b0ec02d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'ASSISTANT', 'SYSTEM', 'TOOL', name='message_role'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_execution_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', sa.String(), nullable=False),
    sa.Column('execution_time_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('calls', sa.Column('intent', sa.String(length=255), nullable=True))
    op.add_column('calls', sa.Column('sentiment', sa.String(length=50), nullable=True))
    op.add_column('calls', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('calls', sa.Column('summary', sa.String(), nullable=True))
    # add_column (unlike create_table) doesn't auto-create a new Enum's
    # Postgres type, so it has to be created explicitly first.
    resolution_status_enum = postgresql.ENUM('RESOLVED', 'ESCALATED', 'ABANDONED', name='resolution_status')
    resolution_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('calls', sa.Column('resolution_status', resolution_status_enum, nullable=True))
    # ### end Alembic commands ###

    # conversation_messages / tool_execution_logs: append-only, same
    # reasoning as audit_logs — a call transcript shouldn't be editable
    # after the fact, so app_user gets no UPDATE/DELETE grant at all.
    for table in ("conversation_messages", "tool_execution_logs"):
        op.execute(f"GRANT SELECT, INSERT ON {table} TO app_user")
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            "USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid)"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'resolution_status')
    op.execute("DROP TYPE resolution_status")
    op.drop_column('calls', 'summary')
    op.drop_column('calls', 'confidence_score')
    op.drop_column('calls', 'sentiment')
    op.drop_column('calls', 'intent')
    op.drop_table('tool_execution_logs')
    op.drop_table('conversation_messages')
    # ### end Alembic commands ###
