"""phase 6 customer 360 memory

Revision ID: ca0641c37b56
Revises: 115365d6f3ea
Create Date: 2026-07-19 21:43:13.637014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ca0641c37b56'
down_revision: Union[str, None] = '115365d6f3ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_interaction', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'phone_number', name='uq_customer_profiles_tenant_phone')
    )
    op.add_column('calls', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_calls_customer_id', 'calls', 'customer_profiles', ['customer_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###

    # customer_profiles is a mutable profile (name/preferences get updated
    # over time), so it gets the normal full-CRUD tenant_isolation grant —
    # unlike the append-only conversation_messages/tool_execution_logs.
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON customer_profiles TO app_user")
    op.execute("ALTER TABLE customer_profiles ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE customer_profiles FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON customer_profiles "
        "USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid)"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_calls_customer_id', 'calls', type_='foreignkey')
    op.drop_column('calls', 'customer_id')
    op.drop_table('customer_profiles')
    # ### end Alembic commands ###
